config/routes.rb
Rails.application.routes.draw do
  resources :votes do
    member do
      get  :invite, to: 'invites#new_many'
      post :invite, to: 'invites#create_many'

      get  :notification, to: 'votes#new_notification'
      post :notification, to: 'votes#send_notification'
    end
    resources :answers
  end

  devise_for :users, :controllers => { :registrations => "registrations" }, :skip => [:sessions]
  as :user do
    get 'login'      => 'devise/sessions#new',     :as => :new_user_session
    post 'login'     => 'devise/sessions#create',  :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  match '/about',   to: 'static_pages#about',   via: 'get'
  root  'static_pages#home'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      created_votes     = current_user.created_votes.includes(:creator)
      invited_votes     = current_user.invitations.includes(:vote).map(&:vote)

      @votes_presenter   = VotePresenter.wrap(created_votes, view_context)
      @invites_presenter = VotePresenter.wrap(invited_votes, view_context)
    end
  end

  def about
  end

end

app/views/static_pages/_hero_unit.html.haml
.device-background
  .device-text
    %h4 Anonymous responses for your e-mail chains
    %p Are you part of an email chain?  Do people ask questions that are uncomfortable to answer in that setting?  Questions like "What did you guys think of the food?" or "Can I invite person X to our fantasy football league?" You might've even felt like waiting for others to respond first before saying anything.
    %p The purpose of Blindee is to take these questions out of your email chains, so that responses are fast, anonymous, and hopefully more genuine.
    = link_to "Learn More", about_path, class: "button"
  .device
    .screen

app/views/static_pages/_invites.html.haml
.invites
  %ul
    - @invites_presenter.each do |vote|
      %li.vote-listing
        = render "vote_ribbon", object: vote
        = render "vote_question", object: vote
        = render "vote_footer", object: vote
      %span.post-time
        Invited #{time_ago_in_words(vote.created_at)} ago by #{vote.creator_email}

app/views/static_pages/_vote_footer.html.haml
.vote-footer
  = link_to icon('eye', 'View'), vote_path(object)
  - if object.creator_is_current_user?
    = link_to icon("envelope-o", "Invite"), invite_vote_path(object)
    = link_to icon('trash-o', 'Delete'), object, method: :delete, data: { confirm: 'Are you sure?' }
  - if object.finished?
    = link_to icon('bar-chart','Results'), vote_answers_path(object)

app/views/static_pages/_vote_question.html.haml
.question
  = link_to object.question, vote_path(object)
  = object.render_vote_count

app/views/static_pages/_vote_ribbon.html.haml
- if !object.current_user_voted?
  .ribbon-wrapper
    .ribbon
      = link_to "Vote!", vote_path(object)

app/views/static_pages/_your_questions.html.haml
.questions
  %ul
    - @votes_presenter.each do |vote|
      %li.vote-listing
        = render "vote_ribbon", object: vote
        = render "vote_question", object: vote
        = render "vote_footer", object: vote
      %span.post-time
        Posted #{time_ago_in_words(vote.created_at)} ago

app/views/static_pages/about.html.haml
.about
  %h2 About
  %hr/
  %br/
  %ul.sample-qs
    %li "Okay if I bring my dog to the beach house?"
    %li "Want to get jerseys for our kickball team?  'Only' $50 per person."
    %li "Does this shirt make me look flabby?"
    %li "What did you guys think of business pitch?"
    %li "Can I invite my brother-in-law to our fantasty football league?"
    %li "Can I bring my boyfriend to the BBQ?"
    %li "Go to the beer festival instead of study session this weekend?"
    %li "What do you think of this project?"
  %br/
  %p
    Get these type of questions out of your email chains and into Blindee for faster,
    and more genuine responses.
  %p I hope you enjoy Blindee, and remember not to take the voting too seriously.
  %br/
  %h4 The Basics
  %br/
  %ul.default-ul
    %li Max invitiations per Blindee Vote: 30
    %li Max choices per Blindee Vote: 5
    %li Blindee votes require 75% participate rate before results can be viewed.
    %li Only voters can view results.  So if you were invited, but didn't vote, you will not see results.
    %li After 2 days, results can been seen by voters regardless of particpation rate.
  %br/
  %h4 Contributors
  %br/
  %p Thank you to Saphiroko for the awesome owl icons.
  %p This website is maintained by @jberczel.  Feel free to tweet questions or suggestions.
  %br/
  %br/

app/views/static_pages/contact.html.haml
.contact
  %h2 Contact
  %p Website is maintained by @Jberczel.  Feel feel to tweet questions or suggestions.

app/views/static_pages/home.html.haml
- if user_signed_in?
  %ul.accordion-tabs-minimal
    %li.tab-header-and-content
      %a.tab-link.invite-link.is-active{:href => "#"}
        = icon("envelope")
        Invites
      .tab-content
        = render "invites"
    %li.tab-header-and-content
      %a.tab-link.my-link{:href => "#"}
        = icon("check-square")
        My Votes
      .tab-content
        = render "your_questions"
- else
  = render "hero_unit"