config/routes.rb
Rails.application.routes.draw do
  resources :votes do
    member do
      get  :invite, to: 'invites#new_many'
      post :invite, to: 'invites#create_many'

      get  :notification, to: 'votes#new_notification'
      post :notification, to: 'votes#send_notification'
    end
    resources :answers
  end

  devise_for :users, :controllers => { :registrations => "registrations" }, :skip => [:sessions]
  as :user do
    get 'login'      => 'devise/sessions#new',     :as => :new_user_session
    post 'login'     => 'devise/sessions#create',  :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  match '/about',   to: 'static_pages#about',   via: 'get'
  root  'static_pages#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(content)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,:hard_wrap=>true,:autolink=>true,:no_intra_emphasis=>true)
    markdown.render(h(content)).html_safe
  end
end

app/views/application/_analytics.html.erb
<script type="text/javascript">

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41079755-4', 'auto');
  ga('send', 'pageview');

</script>

app/views/application/_analytics.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41079755-4', 'auto');
  ga('send', 'pageview');

app/views/application/_flashes.html.haml
#flash
  - flash.each do |key, value|
    %div{:id => "flash_#{key}"}= value

app/views/application/_header.html.haml
%header.centered-navigation
  .centered-navigation-wrapper
    = link_to(image_tag("logo.png"), root_path, class: "mobile-logo")
    %a.centered-navigation-menu-button{:href => ""} MENU
    %ul.centered-navigation-menu
      %li.nav-link= link_to "Home", root_path
      %li.nav-link= link_to "New Vote", new_vote_path
      %li.nav-link.logo
        = link_to(image_tag("logo.png"), root_path, class: "logo")
      %li.nav-link= link_to "Public Votes", votes_path
      %li.nav-link= link_to "About", about_path

app/views/application/_logo.html.haml
= link_to(image_tag('logo.png'), root_path, class: "header")
%h1.title Blindee

app/views/application/_sign_in.html.haml
#sign_in
  - if user_signed_in?
    = current_user.email
    = link_to "(Sign out)", destroy_user_session_path, :method => :delete
  - else
    = link_to "Sign up", new_user_registration_path
    or #{link_to "sign in", new_user_session_path}