config/routes.rb
Rails.application.routes.draw do
  resources :votes do
    member do
      get  :invite, to: 'invites#new_many'
      post :invite, to: 'invites#create_many'

      get  :notification, to: 'votes#new_notification'
      post :notification, to: 'votes#send_notification'
    end
    resources :answers
  end

  devise_for :users, :controllers => { :registrations => "registrations" }, :skip => [:sessions]
  as :user do
    get 'login'      => 'devise/sessions#new',     :as => :new_user_session
    post 'login'     => 'devise/sessions#create',  :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  match '/about',   to: 'static_pages#about',   via: 'get'
  root  'static_pages#home'
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  belongs_to :creator, :class_name => "User"

  has_many :invites, :dependent => :destroy
  has_many :answers, :dependent => :destroy

  validates :question, presence: true, length: { maximum: 140 }
  validates :choices, presence: true, length: { maximum: 140 }
  validates :creator_id, presence: true

  before_save :add_quote

  MAX_CHOICES = 5

  def get_choices
    choices.split(/\r?\n/).select { |c| c =~ /\S+/ }.take(MAX_CHOICES)
  end

  private
    # add quesiton mark to question if user forgets
    def add_quote
      self.question << '?' unless self.question.ends_with?('?')
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  include VotesHelper
  before_action :authenticate_user!
  before_action :set_vote, only: [ :show, :destroy, :new_notification, :send_notification ]
  before_action :already_notified?, only: [ :new_notification, :send_notification ]

  def index
    @votes = Vote.where(public_vote: true).includes(:creator)
    @votes_presenter = VotePresenter.wrap(@votes, view_context)
  end

  def show
    if !@vote_presenter.current_user_invited? && !@vote_presenter.public_vote?
      redirect_to root_path, notice: "Sorry, you weren't invited to this Vote."
    end
  end

  def new
    @vote = current_user.created_votes.build
  end

  def create
    @vote = current_user.created_votes.build(vote_params)
    if @vote.save
      if @vote.public_vote
        redirect_to @vote, :flash => { :success => 'Your public vote was successfully created.' }
      else
        redirect_to invite_vote_path(@vote),  :flash => { :success => 'Vote was successfully created. Now invite some voters!' }
      end
    else
      flash.now[:error] = 'Uh oh, something went wrong.'
      render :new
    end
  end

  def destroy
    if @vote_presenter.creator_is_current_user?
      @vote.destroy
      redirect_to root_path, notice: 'Vote was successfully destroyed.'
    end
  end

  def new_notification
  end

  def send_notification
    Mailer.send_notification(@vote, vote_url(@vote), params[:comment]).deliver
    @vote.update_attributes(:notified => true)
    redirect_to vote_path(@vote), :notice => 'Notifications sent'
  end

  private

  def set_vote
    @vote           = Vote.find(params[:id])
    @vote_presenter = VotePresenter.new(@vote, view_context)
  end

  def vote_params
    params.require(:vote).permit(:question, :choices, :details, :public_vote)
  end

  def already_notified?
    if @vote_presenter.notified? || @vote_presenter.public_vote?
      redirect_to vote_path(@vote), notice: "Already notified."
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper

end

app/views/votes/_answer_choices.html.haml
%ul.default
  - @vote.get_choices.each do |option|
    %li= option

app/views/votes/_answer_form.html.haml
= simple_form_for([@vote, @vote.answers.build]) do |f|
  .radios
    - @vote.get_choices.each do |option|
      = f.label "#{option}", option do
        = f.radio_button :answer, option, class: "icheck-me", data: { skin: "square", color: "pink" }
        = option

  = f.input :comment, label: "comment (optional)"
  %button{:type => "submit"}= icon('check', 'Submit Vote')

app/views/votes/_form.html.haml
= minimal_form_for(@vote) do |f|
  = f.input :question
  = f.text_area :details, rows: 3, placeholder: "Add question details (optional)"
  = f.text_area :choices, rows: 5, placeholder: "Enter answers on each line..."
  %button.button{:type => "submit"}
    = icon('check', 'Create Vote')
  = f.input :public_vote, label: "Public Vote?"

app/views/votes/_invite_form.html.erb
<!-- controller: 'votes', action: 'invite' -->
<%= form_tag invite_vote_path do %>
<%= text_area_tag :invite_emails, nil, rows: 5, placeholder: "Enter e-mails separated by commas" %>
<%= submit_tag "Send Invites", :name => nil, class: "button" %>
<% end %>

app/views/votes/_vote_detail.html.haml
-#public vote does not have status, invites, and notification sections
- if @vote_presenter.public_vote?
  .creator
    %h4= icon('user','created by')
    %hr/
    %p= @vote_presenter.creator_email
  .vote-type
    %h4= icon('unlock-alt','vote type')
    %hr/
    %p Public
- else
  -#private vote section
  .status
    %h4= icon('circle-o-notch', 'status')
    %hr/
    %p
      = @vote_presenter.answers_count
      of #{@vote_presenter.invites_count + 1} votes

  .creator
    %h4= icon('user','created by')
    %hr/
    %p= @vote_presenter.creator_email

  .vote-type
    %h4= icon('lock','vote type')
    %hr/
    %p Private

  .invites-detail
    %h4
      = icon('users')
      invites (#{@vote_presenter.invites_count})
    %hr/
    %p= @vote_presenter.invitees
    - if @vote_presenter.creator_is_current_user? && !@vote_presenter.finished?
      = link_to icon('plus', 'Add Invites'), invite_vote_path, :class => "button"

    - if @vote_presenter.creator_is_current_user? && !@vote_presenter.notifications_sent?
      = link_to icon('mail-forward', 'Notify Invites'), notification_vote_path, :class => "button"

app/views/votes/_vote_q_a.html.haml
%h3= @vote_presenter.question
.question-details= @vote_presenter.details

%h4.choices-header= icon('check-circle-o', 'choices')
%hr/

- if !@vote_presenter.current_user_voted?
  = render 'answer_form'
- else
  = render 'answer_choices'
  - if @vote_presenter.finished?
    = link_to icon("bar-chart", "View Results"), vote_answers_path(@vote), class: "button"

app/views/votes/edit.html.haml
%h1 Editing vote
= render 'form'
= link_to 'Show', @vote
|
\#{link_to 'Back', root_path}

app/views/votes/index.html.haml
.vote-list
  %h2 Public votes
  %hr/
  %p Not very scientific, but any Blindee user can vote here.
  %ul
    - @votes_presenter.each do |vote|
      %li.vote-listing
        .question
          = link_to vote.question, vote
          .vote-count
            = pluralize(vote.answers_count, "vote")
            so far
        .vote-footer
          = link_to icon('eye', 'View'), vote_path(vote)
          = link_to icon('bar-chart', 'Results'), vote_answers_path(vote)

      %span.post-time
        = time_ago_in_words(vote.created_at)
        ago by #{vote.creator_email}

app/views/votes/new.html.haml
.vote-form
  %h1 New blind vote
  = render 'form'

app/views/votes/new_notification.html.haml
.invite-form
  %h2 Notify Invites
  = form_tag notification_vote_path do
    = text_area_tag :comment, nil, rows: 7, placeholder: "Send a reminder or notify your invites about the results."
    %button.button{:type => "submit"}
      = icon('mail-forward', 'Send Notification')
  = link_to icon("eye","Vote details"), vote_path(@vote), class: "button-detail"

app/views/votes/show.html.haml
.q-and-a
  = render "vote_q_a"
.detail
  = render "vote_detail"